### ISSUE TITLE
Missing footnote for "Logarithms of rotations" section

### ISSUE THREAD

**Issue by incognitojam** [jde27/lin-alg#1]
https://github.com/jde27/lin-alg/blob/9a1f774946c65f54ceb5f61f09315400594a8409/la.tex#L859

![image](https://user-images.githubusercontent.com/4038174/54997098-dd815080-4fc2-11e9-978e-af3526e5d92c.png)

There doesn't appear to be a footnote for the asterisk on this section title. Should the asterisk be removed or is the footnote missing?

**Comment by jde27** [comment]
Thanks for your comment! The asterisk is there to denote material I consider too tricky to examine. When I get a chance I'll add a comment about this somewhere in the notes.
